# Generated by Django 3.2.10 on 2024-10-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend_analysis', 'XXXX_add_channel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_length', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trend_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_analysis.trendanalysis')),
            ],
        ),
    ]
