# Generated by Django 5.1.2 on 2024-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_auto_20241024_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
